# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180102_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_cars',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hardware',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='highest_simracing_achievement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='simracing_experience',
            field=models.CharField(blank=True, choices=[('', ''), ('Less than 1 year', 'Less than 1 year'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('4 years', '4 years'), ('5 years', '5 years'), ('More than 5 years', 'More than 5 years')], default='', max_length=20),
        ),
    ]
